### ISSUE TITLE
Switch from NuGet to Bower for client-side packages

### ISSUE THREAD

**Issue by 8aginski** [aspnetboilerplate/aspnetboilerplate-templates#21]
ASP.NET MVC 6 RC1 no longer uses NuGet for the client-side packages like bootstrap and jquery, it uses Bower instead. While it might depend on one's taste which package manager they prefer (I agree with this choice, I never liked the way NuGet handled the client-side packages), it makes sense for ABP to follow to make the future migration to MVC 6 easier.

**Comment by hikalkan** [comment]
After supporting AspNet Core, a new template will be prepared in VS 2015 that uses bower, gulp... etc.
