### ISSUE TITLE
Nuget-update infinite loop for log4net

### ISSUE THREAD

**Issue by patagoniahiker** [aspnetboilerplate/aspnetboilerplate-templates#22]
When I try to update the nuget after downloading from site...

it update log4net, 
then agains asks to update (Castle.Windsor-log4net)
then back again to --->  update log4net, 
then agains asks to update (Castle.Windsor-log4net)....... goes on.

**Comment by hikalkan** [comment]
Log4Net's latest version is not compatible with Castle.Windsor-log4net. So, do not update it (this is the only way for now).
