### ISSUE TITLE
Update-database fails,    Warning! The maximum key length is 900 bytes

### ISSUE THREAD

**Issue by patagoniahiker** [aspnetboilerplate/aspnetboilerplate-templates#23]
Applying explicit migration: 201602161446590_Upgrade_Abp_And_Module_Zero_To_0_8_1.

`Warning! The maximum key length is 900 bytes. The index 'IX_NotificationName_EntityTypeName_EntityId_UserId' has maximum length of 1032 bytes. For some combination of large values, the insert/update operation will fail.`

**Comment by hikalkan** [comment]
It's not a problem. Fixed it in the next version by changing field lenghts.
