### ISSUE TITLE
Main.js and Internet Explorer - Function Expected

### ISSUE THREAD

**Issue by nandaccio** [aspnetboilerplate/aspnetboilerplate-templates#28]
I've tested a generated template with several browsers, there are no issues with Firefox / Chrome / Opera but debugging a project generated based on ABP.NET Boilerplate using Internet Explorer 11 leads to (at every page reload):

![spy](https://cloud.githubusercontent.com/assets/13116598/15181645/b2995522-1788-11e6-99e4-ad51550502b4.jpg)

**Comment by ismcagdas** [comment]
Thanks for informing.
It's related to module zero template actually and which is fixed. There is a missing semi-colon at the end of serializeFormToObject definition. 
Please see this issue https://github.com/aspnetboilerplate/module-zero-template/issues/42
