### ISSUE TITLE
unit test single tenant app problem

### ISSUE THREAD

**Issue by hikalkan** [aspnetboilerplate/aspnetboilerplate-templates#38]
We should update the startup template so it won't create host entities if multitenancy is disabled.
see https://github.com/aspnetboilerplate/aspnetboilerplate/issues/1570

**Comment by ismcagdas** [comment]
Moved to https://github.com/aspnetboilerplate/module-zero-template/issues/82 and https://github.com/aspnetboilerplate/module-zero-core-template/issues/20
