### ISSUE TITLE
Building template results in Error MSB6006: "tsc.exe" exited with code 1.

### ISSUE THREAD

**Issue by albertdev** [aspnetboilerplate/aspnetboilerplate-templates#39]
I've created a sample project based on the online generator but when I try to build it in Visual Studio 2015 I get the following error:

    Error MSB6006: "tsc.exe" exited with code 1.

According to [this StackOverflow Post about that error](http://stackoverflow.com/a/37350294/983949) you can install TypeScript nuget packages. I still had to remove the original TypeScript build tasks from the project file before that works, but now it seems everything builds.

So while I'm no longer blocked, it's weird the templates are failing out of the box. Maybe it's because I just didn't have [TypeScript for Visual Studio 2015](https://www.microsoft.com/en-us/download/details.aspx?id=48593) installed?

**Comment by hikalkan** [comment]
Yes, it requires Typescript 2.0+ for VS 2015 installed. Actually templates does not have typescript code, Abp.Web.Resources nuget package comes with d.ts files so it causes to the problem.

It would be good we should highlight this requirement.

**Comment by ismcagdas** [comment]
Added TypeScript 2.0+ requirement to Startup Template documentation.
