### ISSUE TITLE
I get System.ApplicationException: Could not find content root folder!

### ISSUE THREAD

**Issue by thanhdevapp** [aspnetboilerplate/aspnetboilerplate-templates#43]
Hi !,
Please help me detect, i run in VS 2015 ok ! but i get error whent publish to IIS

My log

````
WARN  2017-02-05 01:52:18,336 [42   ] Abp.BackgroundJobs.BackgroundJobManager  - Castle.MicroKernel.ComponentActivator.ComponentActivatorException: ComponentActivator: could not instantiate ABPnetcore.EntityFramework.ABPnetcoreDbContext ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ApplicationException: Could not find content root folder!
   at ABPnetcore.Web.WebContentDirectoryFinder.CalculateContentRootFolder() in C:\Users\THANHNX\Documents\philongdc\ABPnetcore\src\ABPnetcore.Core\Web\WebContentFolderHelper.cs:line 26
   at ABPnetcore.EntityFramework.ABPnetcoreDbContext.GetConnectionString() in C:\Users\THANHNX\Documents\philongdc\ABPnetcore\src\ABPnetcore.EntityFramework\EntityFramework\ABPnetcoreDbContext.cs:line 37
   at ABPnetcore.EntityFramework.ABPnetcoreDbContext..ctor() in C:\Users\THANHNX\Documents\philongdc\ABPnetcore\src\ABPnetcore.EntityFramework\EntityFramework\ABPnetcoreDbContext.cs:line 30` 
````

My version:
````
    "Abp.AspNetCore": "1.4.1",
    "Abp.Castle.Log4Net": "1.4.1",
    "Abp.HangFire": "1.4.1",
    "Abp.Owin": "1.4.1",
    "Castle.Windsor": "3.4.0",
    "Abp.RedisCache": "1.4.1",
    "Abp.Web.SignalR": "1.4.1"
````

**Comment by hikalkan** [comment]
Hi,

Default constructor is normally only called in development time, by EF command line tool. Have you removed the constructor which takes ``string nameOrConnectionString`` ?

**Comment by thanhdevapp** [comment]
Hi, My DbContext, i'm not remove nameOrConnectionString

`using System.Data.Common;
using System.Data.Entity;
using Abp.Zero.EntityFramework;
using Microsoft.Extensions.Configuration;
using ABPnetcore.Authorization.Roles;
using ABPnetcore.BDS;
using ABPnetcore.Configuration;
using ABPnetcore.MultiTenancy;
using ABPnetcore.Users;
using ABPnetcore.Web;

namespace ABPnetcore.EntityFramework
{
    [DbConfigurationType(typeof(ABPnetcoreDbConfiguration))]
    public class ABPnetcoreDbContext : AbpZeroDbContext<Tenant, Role, User>
    {
        /* Define an IDbSet for each entity of the application */

        public DbSet<BdsPostType> BdsPostType { get; set; }
        public DbSet<BdsPost> BdsPost { get; set; }
        public DbSet<BdsPostExtention> BdsPostExtention { get; set; }
        public DbSet<BdsImage> BdsImage { get; set; }

        public DbSet<Province.Province> Province { get; set; }
        public DbSet<Province.District> District { get; set; }
        public DbSet<Province.Ward> Ward { get; set; }

        /* Default constructor is needed for EF command line tool. */
        public ABPnetcoreDbContext()
            : base(GetConnectionString())
        {

        }

        private static string GetConnectionString()
        {
            var configuration = AppConfigurations.Get(
                WebContentDirectoryFinder.CalculateContentRootFolder()
                );

            return configuration.GetConnectionString(
                ABPnetcoreConsts.ConnectionStringName
                );
        }

        /* This constructor is used by ABP to pass connection string.
         * Notice that, actually you will not directly create an instance of ABPnetcoreDbContext since ABP automatically handles it.
         */
        public ABPnetcoreDbContext(string nameOrConnectionString)
            : base(nameOrConnectionString)
        {

        }

        /* This constructor is used in tests to pass a fake/mock connection. */
        public ABPnetcoreDbContext(DbConnection dbConnection)
            : base(dbConnection, true)
        {

        }

        public ABPnetcoreDbContext(DbConnection dbConnection, bool contextOwnsConnection)
            : base(dbConnection, contextOwnsConnection)
        {

        }
    }

    public class ABPnetcoreDbConfiguration : DbConfiguration
    {
        public ABPnetcoreDbConfiguration()
        {
            SetProviderServices(
                "System.Data.SqlClient",
                System.Data.Entity.SqlServer.SqlProviderServices.Instance
            );
        }
    }
}
`

**Comment by hikalkan** [comment]
Can you try to remove default constructor and publish again to see what happens.

**Comment by thanhdevapp** [comment]
Keep constructor and run with VS it working but, remove default constructor

I remove

> public ABPnetcoreDbContext()
            : base(GetConnectionString())
        { }

I get error

`MigrationsException: The target context 'ABPnetcore.EntityFramework.ABPnetcoreDbContext' is not constructible. Add a default constructor or provide an implementation of IDbContextFactory.
System.Data.Entity.Migrations.DbMigrator..ctor(DbMigrationsConfiguration configuration, DbContext usersContext, DatabaseExistenceState existenceState, bool calledByCreateDatabase)`

**Comment by hikalkan** [comment]
You are publishing to IIS and running the application then getting this exception, right? (or you are using EF migration tool to create/update database?)

**Comment by hikalkan** [comment]
And also, can you share full stack trace so I can understand the code trying to create ABPnetcoreDbContext

**Comment by thanhdevapp** [comment]
1. Everything work when create database with "dotnet cl database update" and rung IIS Express from VS
2. i want publishing to IIS Server but get error, i see log file

I understand my problem , Could not find content root folder => could not get string connection

`WARN  2017-02-05 01:52:18,336 [42   ] Abp.BackgroundJobs.BackgroundJobManager  - Castle.MicroKernel.ComponentActivator.ComponentActivatorException: ComponentActivator: could not instantiate ABPnetcore.EntityFramework.ABPnetcoreDbContext ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ApplicationException: Could not find content root folder!
   at ABPnetcore.Web.WebContentDirectoryFinder.CalculateContentRootFolder() in C:\Users\THANHNX\Documents\philongdc\ABPnetcore\src\ABPnetcore.Core\Web\WebContentFolderHelper.cs:line 26
   at ABPnetcore.EntityFramework.ABPnetcoreDbContext.GetConnectionString() in C:\Users\THANHNX\Documents\philongdc\ABPnetcore\src\ABPnetcore.EntityFramework\EntityFramework\ABPnetcoreDbContext.cs:line 37
   at ABPnetcore.EntityFramework.ABPnetcoreDbContext..ctor() in C:\Users\THANHNX\Documents\philongdc\ABPnetcore\src\ABPnetcore.EntityFramework\EntityFramework\ABPnetcoreDbContext.cs:line 30` `

**Comment by thanhdevapp** [comment]
I resolved with way default connection in constructor 

`private static string GetConnectionString()
        {
            return "Server=localhost; Database=ABPnetcoreDb; User Id=sa; Password=123456";
        }`

**Comment by thanhdevapp** [comment]
Pls Help me detect

**Comment by thanhdevapp** [comment]
I replace function in ABPnetcoreDbContext to get current path it work, please close

private static string GetConnectionString()
        {
            //add new line to get path
            string startupPath = System.IO.Directory.GetCurrentDirectory();
            //remove this line
            //var rootDoc = WebContentDirectoryFinder.CalculateContentRootFolder();
            var configuration = AppConfigurations.Get(startupPath);

            return configuration.GetConnectionString(
                ABPnetcoreConsts.ConnectionStringName
                );
        }

**Comment by Worthy7** [comment]
Hi, I'm using this line to inject config:

`_appConfiguration = AppConfigurations.Get(WebContentDirectoryFinder.CalculateContentRootFolder(), addUserSecrets: true);`

But it causes this same error when deployed to an Azure server. Local running is fine. How can I fix this?

**Comment by ismcagdas** [comment]
@Worthy7 this usage is for development time (running EF migrations). Could you try to use something like this;

```c#
public interface IAppConfigurationAccessor
{
	IConfigurationRoot Configuration { get; }
}


public class AppConfigurationAccessor: IAppConfigurationAccessor, ISingletonDependency
{
	public IConfigurationRoot Configuration { get; }

	public AppConfigurationAccessor(IHostingEnvironment env)
	{
		Configuration = env.GetAppConfiguration();
	}
}
```

**Comment by Worthy7** [comment]
Trying to use this in AppServices, but it's not working because it cannot see `GetAppConfiguration();`

**Comment by ismcagdas** [comment]
@Worthy7 implementation show be defined in the web project. Did you do it like that ?

**Comment by Worthy7** [comment]
It will work I am sure, but I do not need it in my web project. I need to for doing backend things like connecting to Google's api etc. So I need to get my UserSecrets to do that.

**Comment by Worthy7** [comment]
Help, how do I do this?

**Comment by ismcagdas** [comment]
@Worthy7 where do you store setting values ? Is it in your appsettings.json in the web project ?

**Comment by Worthy7** [comment]
UserSecrets on my dev machine, and `Application Settings` on my Azure server.

**Comment by ismcagdas** [comment]
@Worthy7 I didn't have a chance to try but this could help https://docs.microsoft.com/en-us/aspnet/core/security/key-vault-configuration?view=aspnetcore-2.1&tabs=aspnetcore2x.

I think this is not related to ABP. You might find better answers on the web.

**Comment by Worthy7** [comment]
In the end that was the solution. it works fine. It uses UserSecrents on my dev machine, and when published correctly uses the App Settings on Azure.
`Environment.GetEnvironmentVariable("SENDGRID_API_KEY");`

**Comment by Worthy7** [comment]
Actually It seems this way does not allow my dev side UserSecrets to work.
The way that worked for me in the end is using this guide:
https://www.twilio.com/blog/2018/05/user-secrets-in-a-net-core-web-app.html

Add some config classes. Then register them like this:
```
        public IServiceProvider ConfigureServices(IServiceCollection services)
        {
            services.Configure<GoogleApiConfig>(_appConfiguration.GetSection("Authentication:Google"));
            services.Configure<MicrosoftApiConfig>(_appConfiguration.GetSection("Authentication:Microsoft"));
            services.Configure<SendgridApiConfig>(_appConfiguration.GetSection("Sendgrid"));

```

Then just inject `IOptions<MicrosoftApiConfig>` and use as normal - simple and strong!

I feel like this should be explained somewhere in ABP's documentation, just as a "pointer".
Using strong typed config definitely feels like the right way.

**Comment by ismcagdas** [comment]
@Worthy7 thank you for sharing this. We don't want to duplicate ASP.NET's documentation us much as possible.

**Comment by kzmyvr** [comment]
@thanhdevapp @ismcagdas 
My problem is to have a multi-ABP project under the only Solution.
I solved the problem thanks.

```csharp
public ContentManagementDbContext CreateDbContext(string[] args)
        {
            var builder = new DbContextOptionsBuilder<ContentManagementDbContext>();
            //var configuration = AppConfigurations.Get(WebContentDirectoryFinder.CalculateContentRootFolder());
            string startupPath = System.IO.Directory.GetCurrentDirectory();
            //remove this line
            //var rootDoc = WebContentDirectoryFinder.CalculateContentRootFolder();
            var configuration = AppConfigurations.Get(startupPath);
            ContentManagementDbContextConfigurer.Configure(builder, configuration.GetConnectionString(ContentManagementConsts.ConnectionStringName));

            return new ContentManagementDbContext(builder.Options);
        }
```
