### ISSUE TITLE
the process about creating a abp project template ?

### ISSUE THREAD

**Issue by wddpct** [aspnetboilerplate/aspnetboilerplate-templates#45]
when i clicked the http://www.aspnetboilerplate.com/Templates url, selected the template type I wanted,  and inputed he verification code, how do you created the template that could achieve my request. I feel confused. if you can give me some help, help a lot!!!

**Comment by hikalkan** [comment]
No magic. Just renaming placeholders in the solution (https://github.com/aspnetboilerplate/aspnetboilerplate-templates/tree/master/src).
For instance, AbpCompanyName.AbpProjectName.Core becomes YourCompanyName.YourProjectName.Core

**Comment by wddpct** [comment]
which you mean, you just replace the diretory name, '.cs' name and '.sln' name of a exsited template(may be should be copied to other directory in the begining) with specific name(user input) and return the result while someone like me click the create button. am i right

**Comment by hikalkan** [comment]
Yes. Renaming files and find&replace in all files. This is the code if you want: https://gist.github.com/hikalkan/014eecdae7c8d2677b192fcebcf5ba29

**Comment by wddpct** [comment]
thanks a lot. I'm sorry for the late reply
