### ISSUE TITLE
Relative paths do not work when using bundle optimization

### ISSUE THREAD

**Issue by easyest** [aspnetboilerplate/aspnetboilerplate-templates#5]
When using `BundleTable.EnableOptimizations = true;` relative paths to resources do not resolve correctly.

**Comment by hikalkan** [comment]
I think this is a problem of Bundling of MVC. Am I correct?

**Comment by dawsidious** [comment]
Indeed, I think the problem is with the System.Web.Optimization bundling.
(therefore, what I said just before is working great as a workaround :))

Then, it's not a bug from ABP.

**Comment by hikalkan** [comment]
Thanks ;)
