### ISSUE TITLE
Identity 

### ISSUE THREAD

**Issue by digitalgym** [aspnetboilerplate/aspnetboilerplate-templates#6]
Is there an option to add identity to a template?

**Comment by hikalkan** [comment]
Have you checked https://github.com/aspnetboilerplate/module-zero/tree/master/sample

I don't want to add Identity to template since it requires database connection and tables. It goes beyond the purpose of the template. Not eveyone want to use it. I want to keep it simple.

**Comment by digitalgym** [comment]
I just though you could add it as an option when configuring your template at http://aspnetboilerplate.com/. The example is perfect but now I need to migrate what i need into the template thanks all.

**Comment by hikalkan** [comment]
Creating such a wizard is not easy :(
Maybe, in the future.

**Comment by hikalkan** [comment]
I closed this issue since "ABP + module zero" template does it.
