### ISSUE TITLE
Why is the infrastructure layer named xx.EntityFramework?

### ISSUE THREAD

**Issue by maliming** [aspnetboilerplate/aspnetboilerplate-templates#65]
Why is the infrastructure layer named xx.EntityFramework?
xx.Infrastructure etc not more appropriate?

**Comment by hikalkan** [comment]
If you want to collect all infrastructure implementation to this project, yes it would be a better name. But we have just moved EF dependency to this project. You can create a seperated library project for every infrastructure or you can collect all into one infrastructure project.

**Comment by maliming** [comment]
Thanks.
