### ISSUE TITLE
New MVC/EF Template - Generates a TS Upgrade Dialog....

### ISSUE THREAD

**Issue by natiki** [aspnetboilerplate/aspnetboilerplate-templates#66]
_From @natiki on June 29, 2017 11:22_

Hi,

Just downloaded the latest from the website and opened in VS2017 on Win10 Fully Patched and I get:

![image](https://user-images.githubusercontent.com/4738140/27685316-02602706-5d11-11e7-94db-c4771ed256d1.png)

Not a big deal, but it would be better if this dialog was not generated.

_Copied from original issue: aspnetboilerplate/aspnetboilerplate#2270_

**Comment by natiki** [comment]
_From @hikalkan on June 29, 2017 11:40_

We upgrade typescript version in the next release. Thanks.
But this can be a problem for people who don't have the latest typescript.

**Comment by natiki** [comment]
_From @hikalkan on June 29, 2017 11:41_

Also, it would be very good if you can move this issue to the related repository?

**Comment by hikalkan** [comment]
Moved to https://github.com/aspnetboilerplate/module-zero-core-template/issues/74
