### ISSUE TITLE
Castle.Core-log4net Outdated

### ISSUE THREAD

**Issue by Code-Bear** [aspnetboilerplate/aspnetboilerplate-templates#7]
Downloaded the template files and attempted to update all nuget packages to the latest version. I received a warning that it could not update log4net because it could not find a compatible package for Castle.Core-log4net that worked with the latest version of log4net. Found some information on Castle's website that they have no intention of updating that package to work with any of the newer versions of log4net. Are you considering altering the template to remove that outdated package in place of something more current and still in active development?

**Comment by hikalkan** [comment]
Log4Net still one of the most actively used library. Yes, I'm not happy that Castle does not upgrade to latest version but the current version is stable.
Also, it's not hard to change it.
