### ISSUE TITLE
After Downloading New Blank Template Solution is not building and there's a lot of errors with: 

### ISSUE THREAD

**Issue by raskolniko** [aspnetboilerplate/aspnetboilerplate-templates#72]
The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.

**Comment by hikalkan** [comment]
Do you have .net core 2.0 and VS 15.3.3+ installed?

**Comment by raskolniko** [comment]
Sure I have both of them installed. Plus framework 4.7 and VS 2017.

**Comment by hikalkan** [comment]
Did you try to add a reference to assembly netstandard?

**Comment by raskolniko** [comment]
Yes, sure I added and errors became twice more.

**Comment by hikalkan** [comment]
Is that .net core project or .net framework 4.6.1? asp.net core or asp.net mvc5?

**Comment by raskolniko** [comment]
Asp net mvc5 with angular

**Comment by raskolniko** [comment]
Net framework

**Comment by hikalkan** [comment]
OK. We will look on that. Please write all these details before asking for a better support.

**Comment by ismcagdas** [comment]
Hi @raskolniko,

I couldn't find the issue on .Net standard repository but as far as I remember, uninstalling older versios of .net core and installing .net core sdk 2.0 after that solved this problem for me. Can you try that ?

You can also check this issue
https://github.com/dotnet/standard/issues/391

**Comment by raskolniko** [comment]
Hello @ismcagdas , Thank you for your response.
Finally I have resolved problem by installing NETStandard.Library.NETFramework -Version 2.0.0 . Nuget was installing NETStandard.Library by default. 
Thank you guys for your attention 
@hikalkan .

**Comment by ktngoykalolo** [comment]
hello,
I am encountering the same issue. trying to find **NETStandard.Library.NETFramework -Version 2.0.0** but no success.

**Comment by raskolniko** [comment]
@ktngoykalolo https://www.nuget.org/packages/NETStandard.Library/ try to use this

**Comment by ismcagdas** [comment]
@ktngoykalolo do you use VS 2015 v15.3.3 or above ?

**Comment by ktngoykalolo** [comment]
VS 2017 15.3

**Comment by ismcagdas** [comment]
@ktngoykalolo have you tried @raskolniko's suggestion ?

**Comment by easyest** [comment]
Would You please be so kind and indicate the requirements to build the template somewhere? Ar the moment the only thing I find is "Open your solution on Visual Studio 2013 or later."

**Comment by hikalkan** [comment]
VS 2017 15.3 is required. We will fix the information shown after template creation.

**Comment by ismcagdas** [comment]
@easyest it is already done, so I'm closing the issue.
