### ISSUE TITLE
Exit button does not work when Area is used

### ISSUE THREAD

**Issue by frchico** [aspnetboilerplate/aspnetboilerplate-templates#80]
I am developing a project that uses [area] (https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/areas?view=aspnetcore-2.1) and when I am inside an area function, the logout button does not work because the link points to a route that does not exist.

To fix the problem replace

`<li> <a href="@Url.Action("Logout",Account")"> <i class = "material-icons"> input </i> @L ("Logout") </a> </li>`

by code

`<li> @Html.ActionLink (L("Logout"), "Logout", "Account", new {area = string.Empty}) <i class = "material-icons"> input </i> </li>`

in the Views / Shared / Components / SideBarUserArea / Default.cshtml file.

Is this the best way to fix this problem?
I'm using the template that was generated for an MVC Core project with abp v.3.8.0.

**Comment by ismcagdas** [comment]
@frchico thank you for your report. I have created an issue here https://github.com/aspnetboilerplate/module-zero-core-template/issues/267.

What are the urls before and after adding new {area = string.Empty} to the link ?
