### ISSUE TITLE
why tow web.config file ??

### ISSUE THREAD

**Issue by hyzx86** [aspnetboilerplate/aspnetboilerplate-templates#85]
![image](https://user-images.githubusercontent.com/15613121/46902881-69b12700-ceff-11e8-9e8f-8ee3b9b145af.png)

The code generated from https://aspnetboilerplate.com/Templates

![image](https://user-images.githubusercontent.com/15613121/46902891-a67d1e00-ceff-11e8-811b-223ea2391c9f.png)

**Comment by maliming** [comment]
https://github.com/aspnetboilerplate/module-zero-core-template/issues/329
